import React, { useEffect, useMemo, useState } from 'react';
import axios from 'axios';
import { INVESTIGATIONS, LAB_RESULTS, NAV, PATIENTS, RADIOLOGY_STUDIES, USERS, initialStore } from './data.js';

const STORE_KEY = 'ssie-physician-demo-v1';
const clone = value => JSON.parse(JSON.stringify(value));
const now = () => new Intl.DateTimeFormat('en-IN',{dateStyle:'medium',timeStyle:'short'}).format(new Date());
const icon = (name, extra='') => <i className={`bi bi-${name} ${extra}`} aria-hidden="true"/>;
const assetUrl = path => `${import.meta.env.BASE_URL}${path}`;

function Status({children}) {
  const s=String(children).toLowerCase();
  const tone=s.includes('critical')||s.includes('not fit')||s.includes('overdue')?'danger':s.includes('pending')||s.includes('required')||s.includes('high')||s.includes('conditions')||s.includes('abnormal')?'warning':s.includes('fit')||s.includes('completed')||s.includes('normal')||s.includes('reviewed')?'success':'neutral';
  return <span className={`status status-${tone}`}><span className="status-dot"/>{children}</span>;
}

function Login({onLogin}) {
  const [code,setCode]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  const submit=e=>{ e.preventDefault(); setError(''); setBusy(true); setTimeout(()=>{ const user=USERS.find(u=>u.code.trim()===code.trim()); if(!user||password!=='1234'){setError('Employee code or password is incorrect.');setBusy(false);return;} onLogin(user);},350); };
  return <main className="login-page">
    <section className="login-brand" aria-label="SSIE introduction">
      <div className="brand-copy"><span className="eyebrow">Stavya Spine Hospital</span><h1>Clinical decisions,<br/>connected.</h1><p>Physician assessment, medical optimization and perioperative fitness for every admitted spine patient.</p></div>
      <div className="brand-points">
        <div>{icon('person-vcard')}<span><strong>One patient record</strong><small>Shared across the care team</small></span></div>
        <div>{icon('shield-check')}<span><strong>Controlled fitness decisions</strong><small>Role-based and audit ready</small></span></div>
        <div>{icon('bell')}<span><strong>Actionable clinical alerts</strong><small>Critical findings stay visible</small></span></div>
      </div>
    </section>
    <section className="login-panel">
      <form className="login-card" onSubmit={submit} noValidate>
        <img src={assetUrl('stavya-logo.png')} className="login-logo" alt="Stavya Spine Hospital"/>
        <div className="demo-label">SSIE Demonstration Environment</div>
        <h2>Physician sign in</h2><p className="muted">Use your registered employee credentials.</p>
        {error&&<div className="alert alert-danger py-2" role="alert">{icon('exclamation-circle me-2')}{error}</div>}
        <label className="form-label" htmlFor="employee-code">Employee code</label>
        <div className="input-group mb-3"><span className="input-group-text">{icon('person')}</span><input id="employee-code" className="form-control" value={code} onChange={e=>setCode(e.target.value)} autoComplete="username" inputMode="numeric" required autoFocus/></div>
        <label className="form-label" htmlFor="password">Password</label>
        <div className="input-group mb-2"><span className="input-group-text">{icon('lock')}</span><input id="password" type="password" className="form-control" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/></div>
        <p className="form-hint">Demonstration password: <strong>1234</strong></p>
        <button className="btn btn-primary w-100 login-submit" disabled={busy}>{busy?<><span className="spinner-border spinner-border-sm me-2"/>Signing in…</>:<>Sign in securely {icon('arrow-right ms-2')}</>}</button>
        <div className="privacy-note">{icon('shield-lock me-2')}Access is logged. Do not share clinical credentials.</div>
      </form>
    </section>
  </main>;
}

function PatientBanner({patient}){ if(!patient)return null; return <div className="patient-banner">
  <div className="patient-id"><span className="avatar">{patient.initials}</span><div><strong className="patient-name">{patient.name}</strong><p>{patient.uhid} · {patient.admission} · {patient.age}y / {patient.gender}</p></div></div>
  <dl><div><dt>Location</dt><dd>{patient.ward} · {patient.room}/{patient.bed}</dd></div><div><dt>Spine consultant</dt><dd>{patient.consultant}</dd></div><div><dt>Planned procedure</dt><dd>{patient.procedure}</dd></div><div><dt>Allergy</dt><dd className={patient.allergy==='NKDA'?'':'text-danger'}>{patient.allergy}</dd></div><div><dt>NBM</dt><dd>{patient.nbm}</dd></div></dl>
  <div className="patient-flags"><Status>{patient.fitness}</Status><span className="risk-flag">Fall risk: {patient.fall}</span></div>
 </div> }

function Dashboard({go,patients,store}){
 const metrics=[['Awaiting assessment',patients.filter(p=>p.assessment==='In progress').length,'clipboard2-pulse','New'],['Due or overdue',patients.filter(p=>p.due.includes('Overdue')).length,'clock-history','Overdue'],['Abnormal results',patients.filter(p=>['Abnormal','Critical'].includes(p.investigation)).length,'exclamation-diamond','Abnormal result'],['Optimization required',patients.filter(p=>p.fitness==='Optimization Required').length,'activity','Optimization required'],['Fitness pending',patients.filter(p=>p.fitness.includes('Pending')).length,'hourglass-split','Pending'],['Conditionally fit',patients.filter(p=>p.fitness==='Fit with Conditions').length,'signpost-split','Conditionally fit'],['Not fit',patients.filter(p=>p.fitness.includes('Not Fit')).length,'x-octagon','Not fit'],['Review due',patients.filter(p=>p.fitness==='Review Required').length,'arrow-repeat','Review due']];
 return <><PageTitle title="Good morning" subtitle="Physician operations overview · Thursday, 10 September 2026" action={<button className="btn btn-primary" onClick={()=>go('queue')}>{icon('list-task me-2')}Open work queue</button>}/>
 <div className="metric-grid">{metrics.map(([l,n,i,f])=><button key={l} className="metric" onClick={()=>go('queue',f)}><span className="metric-icon">{icon(i)}</span><span><strong>{n}</strong><small>{l}</small></span>{icon('chevron-right metric-arrow')}</button>)}</div>
 <div className="dashboard-grid"><section className="panel"><SectionHead title="Requires attention" subtitle="Prioritized by clinical risk and due time"/><div className="attention-list">{patients.filter(p=>p.risk!=='Moderate'||p.due.includes('Overdue')).slice(0,4).map(p=><button key={p.id} onClick={()=>go('assessment',null,p.id)}><span className={`initials risk-${p.risk.toLowerCase()}`}>{p.initials}</span><span className="attention-main"><strong>{p.name}</strong><small>{p.ward} · {p.procedure}</small></span><span><Status>{p.risk}</Status><small>{p.action}</small></span>{icon('chevron-right')}</button>)}</div></section>
 <section className="panel"><SectionHead title="Recent cross-department updates" subtitle="Shared patient timeline"/><div className="timeline">{[
 ['Laboratory','Demo Patient C','Abnormal ECG posted','3 min'],['IPD Nursing','Demo Patient B','Glucose 286 mg/dL recorded','9 min'],['Anaesthesia','Demo Patient D','Pre-anaesthesia review completed','21 min'],['HDU','Demo Patient F','Potassium correction started','28 min']].map((x,i)=><div key={i}><span className="timeline-mark"/><p><strong>{x[0]}</strong><span>{x[1]} · {x[2]}</span></p><time>{x[3]}</time></div>)}</div></section></div>
 <div className="summary-strip"><div><strong>{store.handovers.filter(x=>!x.ack).length}</strong><span>Unacknowledged handovers</span></div><div><strong>{patients.filter(p=>p.risk==='High'||p.risk==='Critical').length}</strong><span>High-risk patients</span></div><div><strong>2</strong><span>Assessments completed today</span></div><div><strong>1</strong><span>Postoperative review due</span></div></div></>;
}

function PageTitle({title,subtitle,action}){return <header className="page-title"><div><h1>{title}</h1><p>{subtitle}</p></div>{action&&<div>{action}</div>}</header>}
function SectionHead({title,subtitle,action}){return <div className="section-head"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div>{action}</div>}

function WorkQueue({patients,onOpen,initialFilter}){
 const [search,setSearch]=useState(''); const [filter,setFilter]=useState(initialFilter||'All'); const [sort,setSort]=useState('risk');
 useEffect(()=>setFilter(initialFilter||'All'),[initialFilter]);
 const filtered=useMemo(()=>patients.filter(p=>{const q=(p.name+p.uhid+p.admission+p.procedure+p.assigned).toLowerCase(); const ok=!search||q.includes(search.toLowerCase()); const cat=filter==='All'||p.category===filter||(filter==='Pending'&&p.fitness.includes('Pending'))||(filter==='Overdue'&&p.due.includes('Overdue'))||(filter==='New'&&p.assessment==='In progress');return ok&&cat;}).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):({Critical:0,High:1,Moderate:2}[a.risk]-{Critical:0,High:1,Moderate:2}[b.risk])),[patients,search,filter,sort]);
 return <><PageTitle title="Physician work queue" subtitle={`${filtered.length} of ${patients.length} admitted patients shown`} action={<button className="btn btn-outline-primary">{icon('download me-2')}Export CSV</button>}/><section className="panel table-panel"><div className="filterbar"><div className="searchbox">{icon('search')}<input aria-label="Search work queue" placeholder="Search patient, UHID, admission or physician" value={search} onChange={e=>setSearch(e.target.value)}/></div><select aria-label="Filter work queue" value={filter} onChange={e=>setFilter(e.target.value)}>{['All','New','Pending','Overdue','Abnormal result','Optimization required','Fit','Conditionally fit','Not fit','Review due'].map(x=><option key={x}>{x}</option>)}</select><select aria-label="Sort work queue" value={sort} onChange={e=>setSort(e.target.value)}><option value="risk">Risk priority</option><option value="name">Patient name</option></select></div><div className="table-responsive"><table className="table clinical-table"><thead><tr><th>Patient</th><th>Location / surgery</th><th>Comorbidity</th><th>Assessment</th><th>Investigations</th><th>Fitness</th><th>Risk / due</th><th>Required action</th></tr></thead><tbody>{filtered.map(p=><tr key={p.id}><td><button className="patient-link" onClick={()=>onOpen(p.id)}><strong>{p.name}</strong><span>{p.uhid} · {p.age}/{p.gender[0]}</span></button></td><td><strong>{p.ward} · {p.room}/{p.bed}</strong><span>{p.procedure}<br/>{p.surgery}</span></td><td>{p.comorbidity}</td><td><Status>{p.assessment}</Status></td><td><Status>{p.investigation}</Status></td><td><Status>{p.fitness}</Status></td><td><Status>{p.risk}</Status><span>{p.due}</span></td><td><strong>{p.action}</strong><span>{p.assigned}<br/>{p.update}</span></td></tr>)}</tbody></table></div>{!filtered.length&&<Empty title="No patients match this view" text="Clear filters or try a different search."/>}</section></>;
}

function Patients({patients,onOpen}){return <><PageTitle title="Admitted patients" subtitle="Current physician caseload across wards and HDU"/><div className="patient-grid">{patients.map(p=><button className="patient-card" key={p.id} onClick={()=>onOpen(p.id)}><div><span className={`initials risk-${p.risk.toLowerCase()}`}>{p.initials}</span><span><strong>{p.name}</strong><small>{p.uhid} · {p.age}y {p.gender}</small></span></div><Status>{p.fitness}</Status><dl><div><dt>Bed</dt><dd>{p.ward} · {p.room}/{p.bed}</dd></div><div><dt>Surgery</dt><dd>{p.surgery}</dd></div><div><dt>Physician</dt><dd>{p.assigned}</dd></div></dl><p>{p.diagnosis}</p><span className="card-action">Open clinical record {icon('arrow-right')}</span></button>)}</div></>}

function Assessment({patient,user,store,setStore,toast}){
 const saved=store.assessments[patient.id]||{}; const [form,setForm]=useState({complaints:'',history:'',medications:'',bp:'',pulse:'',spo2:'',diagnoses:'',riskSummary:'',optimization:'',impression:'',...saved}); const finalized=saved.status==='Finalized';
 useEffect(()=>setForm({complaints:'',history:'',medications:'',bp:'',pulse:'',spo2:'',diagnoses:'',riskSummary:'',optimization:'',impression:'',...(store.assessments[patient.id]||{})}),[patient.id]);
 const field=(key,label,opts={})=><div className={opts.wide?'field span-2':'field'}><label htmlFor={key}>{label}{opts.required&&<sup>*</sup>}</label>{opts.area?<textarea id={key} rows={opts.rows||3} value={form[key]} disabled={finalized} onChange={e=>setForm({...form,[key]:e.target.value})}/>:<input id={key} value={form[key]} disabled={finalized} onChange={e=>setForm({...form,[key]:e.target.value})}/>}</div>;
 const save=status=>{if(status==='Finalized'&&!user.canSign){toast('Your role can save drafts but cannot finalize assessments.','danger');return;} const item={...form,status,updated:now(),signedBy:status==='Finalized'?user.name:undefined};setStore(s=>({...s,assessments:{...s.assessments,[patient.id]:item},audit:[{id:crypto.randomUUID(),patientId:patient.id,actor:user.name,action:`Assessment ${status.toLowerCase()}`,time:now(),detail:status==='Finalized'?'Digitally signed and locked':'Draft saved'},...s.audit]}));toast(status==='Finalized'?'Assessment finalized and digitally signed.':'Draft saved.');};
 return <><PageTitle title="Physician initial assessment" subtitle={finalized?'Finalized documentation is locked. Addenda remain auditable.':'Structured preoperative medical evaluation'} action={<Status>{saved.status||'New draft'}</Status>}/><section className="panel form-panel"><SectionHead title="Encounter information" subtitle={`Requested by ${patient.consultant} · Planned ${patient.procedure} · ${patient.surgery}`}/><div className="form-grid">{field('complaints','Current complaints',{wide:true,area:true,required:true})}{field('history','Medical history and current control',{wide:true,area:true})}{field('medications','Medication reconciliation and perioperative instructions',{wide:true,area:true})}</div><SectionHead title="Examination"/><div className="form-grid cols-3">{field('bp','Blood pressure (mmHg)')}{field('pulse','Pulse (/min)')}{field('spo2','SpO₂ (%)')}</div><SectionHead title="Assessment and plan"/><div className="form-grid">{field('diagnoses','Active diagnoses / comorbidities',{wide:true,area:true})}{field('riskSummary','Medical risk summary',{wide:true,area:true,required:true})}{field('optimization','Required optimization',{wide:true,area:true})}{field('impression','Physician impression',{wide:true,area:true,required:true})}</div><div className="form-actions"><span>Last saved: {saved.updated||'Not saved'}</span><button className="btn btn-outline-primary" disabled={finalized} onClick={()=>save('Draft')}>Save draft</button><button className="btn btn-primary" disabled={finalized||!user.canSign} onClick={()=>save('Finalized')}>{icon('pen me-2')}Finalize & sign</button></div></section></>;
}

function Optimization({patient,store,setStore,toast}){
 const tasks=store.optimization.filter(x=>x.patientId===patient.id); const [task,setTask]=useState(''); const [owner,setOwner]=useState('IPD Nursing');
 const add=()=>{if(!task.trim())return;setStore(s=>({...s,optimization:[...s.optimization,{id:crypto.randomUUID(),patientId:patient.id,task,owner,priority:'High',due:'Today, 16:00',status:'Pending'}]}));setTask('');toast('Optimization task assigned.');};
 return <><PageTitle title="Review & optimization" subtitle="Cross-department medical optimization plan"/><section className="panel"><SectionHead title="Active plan" subtitle={`${tasks.length} actions for ${patient.name}`}/>{tasks.length?tasks.map(t=><div className="task-row" key={t.id}><button aria-label={`Mark ${t.task} complete`} className={`check ${t.status==='Completed'?'done':''}`} onClick={()=>{setStore(s=>({...s,optimization:s.optimization.map(x=>x.id===t.id?{...x,status:x.status==='Completed'?'Pending':'Completed'}:x)}));toast('Task status updated.')}}>{icon(t.status==='Completed'?'check-lg':'')}</button><div><strong>{t.task}</strong><span>{t.owner} · Due {t.due}</span></div><Status>{t.priority}</Status><Status>{t.status}</Status></div>):<Empty title="No optimization tasks" text="Add an action below when medical optimization is required."/>}<div className="inline-create"><input aria-label="Optimization task" placeholder="Add a clear clinical action" value={task} onChange={e=>setTask(e.target.value)}/><select aria-label="Responsible department" value={owner} onChange={e=>setOwner(e.target.value)}><option>IPD Nursing</option><option>Cardiology</option><option>Laboratory</option><option>HDU</option><option>Physician</option></select><button className="btn btn-primary" onClick={add}>Assign action</button></div></section><InvestigationPanel patient={patient} store={store} setStore={setStore} toast={toast}/></>;
}

function InvestigationPanel({patient,store,setStore,toast}){return <section className="panel mt-3"><SectionHead title="Investigation review" subtitle="Results from the shared patient record"/><div className="table-responsive"><table className="table clinical-table mb-0"><thead><tr><th>Investigation</th><th>Result</th><th>Range</th><th>Flag</th><th>Result time</th><th>Required action</th><th></th></tr></thead><tbody>{INVESTIGATIONS.map(i=><tr key={i.name}><td><strong>{i.name}</strong><span>{i.status} · {i.clinician}</span></td><td>{i.result}</td><td>{i.range}</td><td><Status>{i.flag}</Status></td><td>{i.time}</td><td>{i.action}</td><td><button className="btn btn-sm btn-outline-primary" disabled={store.acknowledgements[`${patient.id}-${i.name}`]} onClick={()=>{setStore(s=>({...s,acknowledgements:{...s.acknowledgements,[`${patient.id}-${i.name}`]:true}}));toast(`${i.name} acknowledged.`)}}>{store.acknowledgements[`${patient.id}-${i.name}`]?'Acknowledged':'Acknowledge'}</button></td></tr>)}</tbody></table></div></section>}

function Laboratory({patient,store,setStore,user,toast}){
 const [filter,setFilter]=useState('All'); const [order,setOrder]=useState(''); const [interpretation,setInterpretation]=useState('');
 const all=LAB_RESULTS.filter(x=>x.patientId===patient.id); const results=all.filter(x=>filter==='All'||(filter==='Abnormal'&&['High','Low','Critical'].includes(x.flag))||(filter==='Pending'&&x.status!=='Final'));
 const reviews=store.labReviews||{}; const orders=store.labOrders||[];
 const placeOrder=()=>{if(!order.trim())return;setStore(s=>({...s,labOrders:[{id:crypto.randomUUID(),patientId:patient.id,test:order,status:'Ordered',priority:'Routine',orderedBy:user.name,time:now()},...(s.labOrders||[])]}));setOrder('');toast('Laboratory order sent to the shared investigation workflow.');};
 const review=(item)=>{setStore(s=>({...s,labReviews:{...(s.labReviews||{}),[item.id]:{acknowledged:true,interpretation:interpretation.trim()||'Reviewed; action documented in physician plan.',physician:user.name,time:now()}}}));setInterpretation('');toast(`${item.test} reviewed and acknowledged.`)};
 return <><PageTitle title="Laboratory results" subtitle="Physician review of laboratory investigations from the shared patient record" action={<select className="page-select" aria-label="Laboratory result filter" value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option><option>Abnormal</option><option>Pending</option></select>}/>
 <div className="result-metrics"><button onClick={()=>setFilter('All')}><span>Total results</span><strong>{all.length}</strong></button><button onClick={()=>setFilter('Abnormal')}><span>Abnormal / critical</span><strong>{all.filter(x=>['High','Low','Critical'].includes(x.flag)).length}</strong></button><button onClick={()=>setFilter('Pending')}><span>Pending</span><strong>{all.filter(x=>x.status!=='Final').length}</strong></button><div><span>Acknowledged</span><strong>{all.filter(x=>reviews[x.id]?.acknowledged).length}</strong></div></div>
 <section className="panel table-panel"><SectionHead title="Result review" subtitle={`${results.length} results for ${patient.name}`}/><div className="table-responsive"><table className="table clinical-table result-table"><thead><tr><th>Panel / test</th><th>Specimen</th><th>Result</th><th>Reference</th><th>Flag</th><th>Collection / report</th><th>Required action</th><th>Physician review</th></tr></thead><tbody>{results.map(x=><tr key={x.id}><td><strong>{x.test}</strong><span>{x.panel} · {x.lab}</span></td><td>{x.specimen}</td><td><strong className={x.flag==='Critical'?'text-danger':''}>{x.result}</strong></td><td>{x.range||'—'}</td><td><Status>{x.flag}</Status></td><td>{x.collected}<span>Reported: {x.reported}</span></td><td>{x.action}</td><td>{reviews[x.id]?<div className="reviewed"><Status>Reviewed</Status><span>{reviews[x.id].physician}<br/>{reviews[x.id].time}</span></div>:x.status==='Final'?<button className="btn btn-sm btn-outline-primary" onClick={()=>review(x)}>Acknowledge</button>:<Status>Awaiting result</Status>}</td></tr>)}</tbody></table></div>{!results.length&&<Empty title="No laboratory results in this view" text="Choose another filter or place a new investigation order."/>}</section>
 <section className="panel mt-3"><SectionHead title="Interpretation and new order" subtitle="The next acknowledgement will include the interpretation below"/><div className="lab-actions"><div className="field"><label htmlFor="lab-interpretation">Physician interpretation</label><textarea id="lab-interpretation" rows="2" value={interpretation} onChange={e=>setInterpretation(e.target.value)} placeholder="Clinical significance and required action"/></div><div className="field"><label htmlFor="lab-order">Laboratory investigation</label><input id="lab-order" value={order} onChange={e=>setOrder(e.target.value)} placeholder="e.g. Repeat serum potassium in 4 hours"/></div><button className="btn btn-primary align-self-end" onClick={placeOrder}>Place lab order</button></div>{orders.filter(x=>x.patientId===patient.id).map(x=><div className="compact-order" key={x.id}>{icon('droplet-half')}<span><strong>{x.test}</strong><small>{x.time} · {x.orderedBy}</small></span><Status>{x.status}</Status></div>)}</section></>;
}

function Radiology({patient,store,setStore,user,toast}){
 const [filter,setFilter]=useState('All'); const [order,setOrder]=useState(''); const studies=RADIOLOGY_STUDIES.filter(x=>x.patientId===patient.id); const visible=studies.filter(x=>filter==='All'||x.modality===filter||(filter==='Pending'&&x.status!=='Final report')); const reviews=store.radiologyReviews||{}; const orders=store.radiologyOrders||[];
 const markReviewed=x=>{setStore(s=>({...s,radiologyReviews:{...(s.radiologyReviews||{}),[x.id]:{physician:user.name,time:now()}},audit:[{id:crypto.randomUUID(),patientId:patient.id,actor:user.name,action:`Radiology reviewed: ${x.study}`,time:now(),detail:x.impression},...s.audit]}));toast(`${x.study} marked reviewed.`)};
 const placeOrder=()=>{if(!order.trim())return;setStore(s=>({...s,radiologyOrders:[{id:crypto.randomUUID(),patientId:patient.id,study:order,status:'Requested',orderedBy:user.name,time:now()},...(s.radiologyOrders||[])]}));setOrder('');toast('Radiology request sent to the shared imaging workflow.');};
 return <><PageTitle title="Radiology imaging" subtitle="Reports and physician review for diagnostic imaging" action={<select className="page-select" aria-label="Radiology modality filter" value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option><option>MRI</option><option>X-ray</option><option>Pending</option></select>}/>
 <div className="result-metrics"><button onClick={()=>setFilter('All')}><span>Total studies</span><strong>{studies.length}</strong></button><button onClick={()=>setFilter('MRI')}><span>MRI</span><strong>{studies.filter(x=>x.modality==='MRI').length}</strong></button><button onClick={()=>setFilter('Pending')}><span>Awaiting report</span><strong>{studies.filter(x=>x.status!=='Final report').length}</strong></button><div><span>Physician reviewed</span><strong>{studies.filter(x=>reviews[x.id]).length}</strong></div></div>
 <section className="radiology-list">{visible.map(x=><article className="panel radiology-card" key={x.id}><div className="modality-tile">{icon(x.modality==='MRI'?'magnet':'bounding-box-circles')}<span>{x.modality}</span></div><div className="study-main"><div className="study-title"><div><h2>{x.study}</h2><p>{x.region} · Performed {x.performed}</p></div><Status>{x.flag}</Status></div><dl><div><dt>Status</dt><dd><Status>{x.status}</Status></dd></div><div><dt>Radiologist</dt><dd>{x.radiologist}</dd></div><div><dt>Ordered</dt><dd>{x.ordered}</dd></div></dl><details><summary>View diagnostic report</summary><div className="report-body"><strong>Impression</strong><p>{x.impression}</p></div></details></div><div className="study-action">{reviews[x.id]?<><Status>Reviewed</Status><small>{reviews[x.id].physician}<br/>{reviews[x.id].time}</small></>:x.status==='Final report'?<button className="btn btn-outline-primary" onClick={()=>markReviewed(x)}>Mark reviewed</button>:<Status>Report pending</Status>}</div></article>)}</section>{!visible.length&&<Empty title="No radiology studies in this view" text="Choose another modality or create a new imaging request."/>}
 <section className="panel mt-3"><SectionHead title="New imaging request" subtitle="Orders remain visible to Radiology and the shared patient timeline"/><div className="inline-create"><input aria-label="Radiology investigation" value={order} onChange={e=>setOrder(e.target.value)} placeholder="e.g. Portable chest X-ray PA"/><select aria-label="Radiology priority"><option>Routine</option><option>Urgent</option><option>STAT</option></select><button className="btn btn-primary" onClick={placeOrder}>Request imaging</button></div>{orders.filter(x=>x.patientId===patient.id).map(x=><div className="compact-order" key={x.id}>{icon('radioactive')}<span><strong>{x.study}</strong><small>{x.time} · {x.orderedBy}</small></span><Status>{x.status}</Status></div>)}</section></>;
}

function Fitness({patient,user,store,setStore,toast}){
 const existing=store.fitness[patient.id]||{}; const [decision,setDecision]=useState(existing.decision||'Assessment Pending'); const [conditions,setConditions]=useState(existing.conditions||''); const [risk,setRisk]=useState(''); const [error,setError]=useState('');
 useEffect(()=>{const x=store.fitness[patient.id]||{};setDecision(x.decision||'Assessment Pending');setConditions(x.conditions||'');setRisk(x.risk||'');setError('')},[patient.id]);
 const save=()=>{if(!user.canSign){setError('Your role cannot issue final surgical fitness.');return;} if((decision==='Fit with Conditions'||decision.includes('Not Fit'))&&!conditions.trim()){setError('Conditions or reason and next review plan are required.');return;} if(!risk.trim()){setError('Medical risk summary is required.');return;} const d=new Date();d.setDate(d.getDate()+3);const validity=d.toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'});setStore(s=>({...s,fitness:{...s.fitness,[patient.id]:{decision,conditions,risk,validity,signedBy:user.name,signedAt:now()}},audit:[{id:crypto.randomUUID(),patientId:patient.id,actor:user.name,action:`Fitness: ${decision}`,time:now(),detail:conditions||'No additional conditions'},...s.audit]}));toast('Fitness decision signed and shared with the care team.');};
 return <><PageTitle title="Surgical fitness" subtitle="Physician medical fitness does not replace anaesthesia clearance" action={<Status>{existing.decision||patient.fitness}</Status>}/><section className="panel form-panel"><div className="safety-note">{icon('shield-exclamation')}<div><strong>Controlled clinical action</strong><p>Final decisions are shared with Spine Surgery, Anaesthesia, Nursing, MO and OT.</p></div></div>{error&&<div className="alert alert-danger" role="alert">{error}</div>}<div className="record-summary"><div><span>Proposed procedure</span><strong>{patient.procedure}</strong></div><div><span>Planned date</span><strong>{patient.surgery}</strong></div><div><span>Investigation status</span><Status>{patient.investigation}</Status></div></div><div className="form-grid"><div className="field span-2"><label htmlFor="risk-summary">Medical risk summary<sup>*</sup></label><textarea id="risk-summary" rows="3" value={risk} onChange={e=>setRisk(e.target.value)}/></div><div className="field"><label htmlFor="decision">Final decision</label><select id="decision" value={decision} onChange={e=>setDecision(e.target.value)}>{['Assessment Pending','Investigations Pending','Optimization Required','Review Required','Fit for Proposed Surgery','Fit with Conditions','Temporarily Not Fit','Not Fit','Fitness Withdrawn','Fitness Expired'].map(x=><option key={x}>{x}</option>)}</select></div><div className="field"><label htmlFor="validity">Fitness validity</label><input id="validity" value="3 days from signature" disabled/></div><div className="field span-2"><label htmlFor="conditions">Conditions, precautions, reason or next review plan</label><textarea id="conditions" rows="4" value={conditions} onChange={e=>setConditions(e.target.value)}/></div></div><div className="form-actions"><span>{existing.signedAt?`Signed ${existing.signedAt} by ${existing.signedBy}`:'Not yet signed'}</span><button className="btn btn-primary" disabled={!user.canSign} onClick={save}>{icon('patch-check me-2')}Sign fitness decision</button></div></section></>;
}

function Orders({patient,store,setStore,toast}){const [type,setType]=useState('Medication order');const [instruction,setInstruction]=useState('');const add=()=>{if(!instruction.trim())return;setStore(s=>({...s,orders:[{id:crypto.randomUUID(),patientId:patient.id,type,instruction,priority:'Routine',status:'Active',orderedAt:now()},...s.orders]}));setInstruction('');toast('Order created and sent to the shared workflow.');};const items=store.orders.filter(x=>x.patientId===patient.id);return <><PageTitle title="Medical orders" subtitle="Orders flow to medication management and nursing execution"/><section className="panel"><div className="inline-create order-create"><select aria-label="Order type" value={type} onChange={e=>setType(e.target.value)}>{['Medication order','Investigation order','Monitoring order','Oxygen order','Diabetic-management instruction','Specialist referral','Review schedule'].map(x=><option key={x}>{x}</option>)}</select><input aria-label="Order instruction" placeholder="Instruction, dose, route, frequency and indication" value={instruction} onChange={e=>setInstruction(e.target.value)}/><button className="btn btn-primary" onClick={add}>Place order</button></div>{items.length?items.map(o=><div className="order-row" key={o.id}><span className="order-icon">{icon('journal-plus')}</span><div><strong>{o.type}</strong><p>{o.instruction}</p><small>{o.orderedAt} · Shared with IPD Nursing</small></div><Status>{o.status}</Status></div>):<Empty title="No physician orders for this patient" text="Create an order using the controlled form above."/>}</section></>}

function Notes({patient,store,setStore,user,toast}){const [note,setNote]=useState('');const [type,setType]=useState('Preoperative review');const add=()=>{if(!note.trim())return;setStore(s=>({...s,notes:[{id:crypto.randomUUID(),patientId:patient.id,type,note,author:user.name,time:now()},...s.notes]}));setNote('');toast('Progress note signed.');};return <><PageTitle title="Progress notes" subtitle="Structured medical follow-up and review"/><section className="panel form-panel"><div className="form-grid"><div className="field"><label>Note type</label><select value={type} onChange={e=>setType(e.target.value)}>{['Preoperative review','Postoperative medical review','Deterioration review','High glucose','Hypertension','Fever','Hypoxia','Electrolyte abnormality','Discharge medical advice'].map(x=><option key={x}>{x}</option>)}</select></div><div/><div className="field span-2"><label>Assessment and plan</label><textarea rows="5" value={note} onChange={e=>setNote(e.target.value)} placeholder="Subjective findings, objective findings, investigation review, plan and review timing"/></div></div><div className="form-actions"><span>Signed as {user.name}</span><button className="btn btn-primary" onClick={add}>Sign progress note</button></div></section>{store.notes.filter(x=>x.patientId===patient.id).map(n=><section className="panel note" key={n.id}><div><Status>{n.type}</Status><time>{n.time}</time></div><p>{n.note}</p><small>{icon('pen me-1')} {n.author}</small></section>)}</>}

function Handover({patients,store,setStore,toast}){return <><PageTitle title="Physician handover" subtitle="Unacknowledged high-risk items remain visible until accepted"/><section className="panel table-panel"><div className="table-responsive"><table className="table clinical-table"><thead><tr><th>Patient</th><th>Current issue</th><th>Risk</th><th>Pending / required review</th><th>Assigned physician</th><th>Acknowledgement</th></tr></thead><tbody>{store.handovers.map(h=>{const p=patients.find(x=>x.id===h.patientId);return <tr key={h.id}><td><strong>{p.name}</strong><span>{p.uhid} · {p.ward}</span></td><td>{h.issue}</td><td><Status>{h.risk}</Status></td><td>{h.pending}<span>{h.review}</span></td><td>{h.assigned}</td><td><button className="btn btn-sm btn-outline-primary" disabled={h.ack} onClick={()=>{setStore(s=>({...s,handovers:s.handovers.map(x=>x.id===h.id?{...x,ack:true}:x)}));toast('Handover acknowledged.')}}>{h.ack?'Acknowledged':'Acknowledge'}</button></td></tr>})}</tbody></table></div></section></>}

function Reports({patients}){const data=[['Fit for surgery',patients.filter(p=>p.fitness==='Fit for Proposed Surgery').length],['Fit with conditions',patients.filter(p=>p.fitness==='Fit with Conditions').length],['Optimization required',patients.filter(p=>p.fitness==='Optimization Required').length],['Not fit / temporarily not fit',patients.filter(p=>p.fitness.includes('Not Fit')).length],['Review or investigations pending',patients.filter(p=>p.fitness.includes('Pending')||p.fitness==='Review Required').length]];return <><PageTitle title="Physician reports" subtitle="Operational quality and turnaround indicators" action={<button className="btn btn-outline-primary">{icon('download me-2')}Export CSV</button>}/><div className="report-metrics"><div><span>Median assessment TAT</span><strong>48 min</strong><small>Target under 60 min</small></div><div><span>Critical result acknowledgement</span><strong>11 min</strong><small>Target under 15 min</small></div><div><span>Completed today</span><strong>2</strong><small>1 signed, 1 draft</small></div></div><section className="panel"><SectionHead title="Current fitness outcomes" subtitle="Admitted physician caseload"/>{data.map(([l,v])=><div className="bar-row" key={l}><span>{l}</span><div><i style={{width:`${Math.max(8,v/patients.length*100)}%`}}/></div><strong>{v}</strong></div>)}</section></>}

function Master({user}){if(user.role!=='System Admin')return <Restricted/>;return <><PageTitle title="Department master" subtitle="Admin-only physician configuration"/><div className="master-grid">{[['Physician users','6','people'],['Roles & permissions','5 roles','shield-lock'],['Medical conditions','28','heart-pulse'],['Investigation master','34','eyedropper'],['Fitness validity','3 days','calendar-check'],['Alert thresholds','12','bell'],['Order templates','16','journal-text'],['Escalation matrix','8 paths','diagram-3']].map(x=><button key={x[0]}>{icon(x[2])}<span><strong>{x[0]}</strong><small>{x[1]} configured</small></span>{icon('chevron-right')}</button>)}</div></>}
function Restricted(){return <div className="state"><span>{icon('shield-lock')}</span><h2>Permission required</h2><p>Your role cannot access this page. Contact the Physician Department Admin if access is required.</p></div>}
function Empty({title,text}){return <div className="empty"><span>{icon('inbox')}</span><strong>{title}</strong><p>{text}</p></div>}

export default function App(){
 const [user,setUser]=useState(()=>{try{return JSON.parse(sessionStorage.getItem('ssie-user'))}catch{return null}}); const [page,setPage]=useState(location.hash.replace('#/','')||'dashboard'); const [selected,setSelected]=useState(()=>sessionStorage.getItem('ssie-patient')||'p2'); const [queueFilter,setQueueFilter]=useState(null); const [mobile,setMobile]=useState(false); const [toastState,setToastState]=useState(null); const [store,setStoreState]=useState(()=>{try{return JSON.parse(localStorage.getItem(STORE_KEY))||clone(initialStore)}catch{return clone(initialStore)}});
 useEffect(()=>localStorage.setItem(STORE_KEY,JSON.stringify(store)),[store]);
 useEffect(()=>{const handler=()=>setPage(location.hash.replace('#/','')||'dashboard');addEventListener('hashchange',handler);return()=>removeEventListener('hashchange',handler)},[]);
 axios.defaults.headers.common['X-SSIE-Demo']='physician-module';
 const setStore=fn=>setStoreState(fn); const patient=PATIENTS.find(p=>p.id===selected)||PATIENTS[0];
 const toast=(message,tone='success')=>{setToastState({message,tone});setTimeout(()=>setToastState(null),3200)};
 const go=(next,filter=null,id=null)=>{if(id){setSelected(id);sessionStorage.setItem('ssie-patient',id)}setQueueFilter(filter);location.hash=`#/${next}`;setPage(next);setMobile(false);};
 if(!user)return <Login onLogin={u=>{sessionStorage.setItem('ssie-user',JSON.stringify(u));setUser(u)}}/>;
 const openPatient=id=>go('assessment',null,id);
 const patientPage=['assessment','optimization','fitness','orders','laboratory','radiology','notes'].includes(page);
 let content;
 if(page==='dashboard')content=<Dashboard go={go} patients={PATIENTS} store={store}/>;
 else if(page==='queue')content=<WorkQueue patients={PATIENTS} onOpen={openPatient} initialFilter={queueFilter}/>;
 else if(page==='patients'||page==='completed')content=<Patients patients={page==='completed'?PATIENTS.filter(p=>p.assessment==='Completed'):PATIENTS} onOpen={openPatient}/>;
 else if(page==='assessment')content=<Assessment patient={patient} user={user} store={store} setStore={setStore} toast={toast}/>;
 else if(page==='optimization')content=<Optimization patient={patient} store={store} setStore={setStore} toast={toast}/>;
 else if(page==='fitness')content=<Fitness patient={patient} user={user} store={store} setStore={setStore} toast={toast}/>;
 else if(page==='orders')content=<Orders patient={patient} store={store} setStore={setStore} toast={toast}/>;
 else if(page==='laboratory')content=<Laboratory patient={patient} store={store} setStore={setStore} user={user} toast={toast}/>;
 else if(page==='radiology')content=<Radiology patient={patient} store={store} setStore={setStore} user={user} toast={toast}/>;
 else if(page==='notes')content=<Notes patient={patient} store={store} setStore={setStore} user={user} toast={toast}/>;
 else if(page==='handover')content=<Handover patients={PATIENTS} store={store} setStore={setStore} toast={toast}/>;
 else if(page==='reports')content=<Reports patients={PATIENTS}/>;
 else if(page==='master')content=<Master user={user}/>;
 else content=<Restricted/>;
 return <div className="app-shell">
  <a href="#main" className="skip-link">Skip to main content</a>
  <aside className={`sidebar ${mobile?'open':''}`}><div className="sidebar-brand"><img src={assetUrl('stavya-logo.png')} alt="Stavya"/><button className="icon-btn mobile-close" aria-label="Close navigation" onClick={()=>setMobile(false)}>{icon('x-lg')}</button></div><div className="module-name"><span>SSIE</span><strong>Physician Medicine</strong><small>Demonstration environment</small></div><nav aria-label="Physician module">{NAV.map(([id,i,label])=><button key={id} className={page===id?'active':''} onClick={()=>go(id)}>{icon(i)}<span>{label}</span>{id==='handover'&&store.handovers.some(x=>!x.ack)&&<b>{store.handovers.filter(x=>!x.ack).length}</b>}</button>)}</nav><div className="sidebar-footer"><div className="user-mini"><span>{user.name.split(' ').filter(x=>x!=='Dr.').slice(0,2).map(x=>x[0]).join('')}</span><div><strong>{user.name}</strong><small>{user.role}</small></div></div><button className="signout" onClick={()=>{sessionStorage.removeItem('ssie-user');setUser(null)}}>{icon('box-arrow-left')} Sign out</button></div></aside>
  {mobile&&<button className="sidebar-scrim" aria-label="Close navigation" onClick={()=>setMobile(false)}/>}<div className="app-main"><header className="topbar"><button className="icon-btn menu-btn" aria-label="Open navigation" onClick={()=>setMobile(true)}>{icon('list')}</button><div className="breadcrumb"><span>SSIE Clinical</span>{icon('chevron-right')}<strong>{NAV.find(x=>x[0]===page)?.[2]||'Physician'}</strong></div><div className="top-actions"><button className="icon-btn" aria-label="Clinical alerts">{icon('bell')}<b>3</b></button><span className="live"><i/>Live clinical record</span></div></header>{patientPage&&<PatientBanner patient={patient}/>}<main id="main" className="content">{content}</main><footer className="app-footer"><span>SSIE Clinical · Stavya Spine Hospital</span><span>Demo data · Last synced just now</span></footer></div>
  {toastState&&<div className={`app-toast ${toastState.tone}`} role="status">{icon(toastState.tone==='danger'?'exclamation-triangle':'check-circle')} {toastState.message}</div>}
 </div>;
}
